title: stonebat
email: stonebat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Developer & AI Enthusiast
github_username:  stonebat
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
