title: Won Cho
email: stonebat@gmail.com
developer: "Developer & AI Enthusiast"
portfolio: "/portfolio"
github_username:  stonebat
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
